"""Add modified_at field - TbSubject, TbKaMessage

Revision ID: 0858da9920fb
Revises: 5cd4db0d1941
Create Date: 2024-09-12 01:28:49.689471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0858da9920fb'
down_revision: Union[str, None] = '5cd4db0d1941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TbKaMessage', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.add_column('TbSubject', sa.Column('modified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TbSubject', 'modified_at')
    op.drop_column('TbKaMessage', 'modified_at')
    # ### end Alembic commands ###
