"""Rename modified_at to updated_at and ORM update automatically  - TbSubject, TbKaMessage

Revision ID: 47b9d84b364c
Revises: 0858da9920fb
Create Date: 2024-09-12 01:33:17.531236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '47b9d84b364c'
down_revision: Union[str, None] = '0858da9920fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TbKaMessage', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('TbKaMessage', 'modified_at')
    op.add_column('TbSubject', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('TbSubject', 'modified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TbSubject', sa.Column('modified_at', mysql.DATETIME(), nullable=True))
    op.drop_column('TbSubject', 'updated_at')
    op.add_column('TbKaMessage', sa.Column('modified_at', mysql.DATETIME(), nullable=True))
    op.drop_column('TbKaMessage', 'updated_at')
    # ### end Alembic commands ###
