"""Check migration changes

Revision ID: 6793d20f0dd9
Revises: e214b48d6a8d
Create Date: 2024-09-09 00:16:25.280527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6793d20f0dd9'
down_revision: Union[str, None] = 'e214b48d6a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
