"""Add essential fields - TbKaMessage

Revision ID: 6bd872082c90
Revises: 9b74ee3bbad8
Create Date: 2024-09-10 14:17:45.584688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6bd872082c90'
down_revision: Union[str, None] = '9b74ee3bbad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TbKaMessage', sa.Column('chat_id', sa.BigInteger(), nullable=False))
    op.add_column('TbKaMessage', sa.Column('client_message_id', sa.BigInteger(), nullable=False))
    op.add_column('TbKaMessage', sa.Column('room_id', sa.BigInteger(), nullable=False))
    op.add_column('TbKaMessage', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.add_column('TbKaMessage', sa.Column('deleted', sa.String(length=1), nullable=True))
    op.alter_column('TbKaMessage', 'last_sent_at',
               existing_type=mysql.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.add_column('TbSubject', sa.Column('last_sent_tb_ka_message_id', sa.String(length=32), nullable=True))
    op.add_column('TbSubject', sa.Column('deleted', sa.String(length=1), nullable=True))
    op.alter_column('TbSubject', 'last_sent_at',
               existing_type=mysql.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_column('TbSubject', 'last_sent_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TbSubject', sa.Column('last_sent_message_id', mysql.VARCHAR(length=32), nullable=True))
    op.alter_column('TbSubject', 'last_sent_at',
               existing_type=sa.Integer(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.drop_column('TbSubject', 'deleted')
    op.drop_column('TbSubject', 'last_sent_tb_ka_message_id')
    op.alter_column('TbKaMessage', 'last_sent_at',
               existing_type=sa.Integer(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.drop_column('TbKaMessage', 'deleted')
    op.drop_column('TbKaMessage', 'user_id')
    op.drop_column('TbKaMessage', 'room_id')
    op.drop_column('TbKaMessage', 'client_message_id')
    op.drop_column('TbKaMessage', 'chat_id')

    # ### end Alembic commands ###
